### ISSUE TITLE
MAC Telnet from MT disconnect after login

### ISSUE THREAD

**Issue by dr4g0nsr** [haakonnessjoen/MAC-Telnet#16] opened 2015-11-11 09:36 UTC
I have installed MAC-Telnet on Ubuntu 12 and ran mactelnetd.
I can see server just fine in neighbour discovery.
MAC Ping works.
When i try to mac telnet i got asked for username and password, when i eneter them i see ubuntu welcome text and console prompt (where i should be able to type commands).
After that i got disconnect and both mac telnet and ping are not working anymore until i kill mactelnetd and start again.

**Comment by haakonnessjoen** [comment] 2015-11-11 09:43
Do you se anything in the syslog of the machine running mactelnetd?

**Comment by dr4g0nsr** [comment] 2015-11-11 10:04
This is all i see in syslog:
Nov 11 10:29:15 fenrir1 mactelnetd[9908]: Bound to 0.0.0.0:20561
Nov 11 10:29:15 fenrir1 mactelnetd[9908]: Listening on eth0 for e4:11:5b:b7:e8:ee
Nov 11 10:29:15 fenrir1 mactelnetd[9908]: Listening on eth2 for e4:11:5b:b7:e8:ef
Nov 11 10:29:32 fenrir1 mactelnetd[9909]: (15873) New connection from 4c:5e:c:64:70:78.
Nov 11 10:29:32 fenrir1 mactelnetd[9911]: (15873) User root logged in.
Nov 11 10:29:36 fenrir1 mactelnetd[9909]: (15873) Connection to user root closed.

**Comment by haakonnessjoen** [comment] 2015-11-11 10:10
Have you tried downloading latest version from here, and checked if it works just as bad?

Just clone the project, and compile with make all, and stop your old mactelnetd, and run the new with sudo ./mactelnetd -n

**Comment by dr4g0nsr** [comment] 2015-11-11 10:12
I cloned this repo before 2 hours.
Thing is that same version works on another identical machine.
Only difference is that non-working machine have alot of pppoe user connections while other one (that works) does not.

**Comment by haakonnessjoen** [comment] 2015-11-11 10:14
Interesting, maybe it has something to do with all the different interfaces. Would it be possible for me to get access to the server that does not work, since I cannot reproduce the problem here.. In that case, send me a mail at haakon.nessjoen@gmail.com

**Comment by dr4g0nsr** [comment] 2015-11-11 10:16
I will soon start pppoe server on working machine and see if that would break it.

**Comment by dr4g0nsr** [comment] 2015-11-16 11:11
It works on other machine... identical one.

**Comment by haakonnessjoen** [comment] 2016-08-07 20:20
I'm closing this because there is not enough info. If you or someone can reproduce this issue, please reopen this issue, and send pcap files of the network traffic while reproducing the issue.

**Closed by haakonnessjoen** 2016-08-07 20:20 UTC
